/* BioLabs Research: customer reviews.
   Lives outside the docroot (/opt/shop-consent/reviews.js), served as /reviews.js and injected into <head> by nginx sub_filter, same as
   restock.js: pages are regenerated by third-party agents, nothing is written inside them. Two jobs, told apart by the address:
   - /products/<slug>: asks GET /api/reviews?slug= and shows the approved reviews ("Customer reviews", name, "Verified purchase", month, text)
     before the "pairs well" rail. Nothing approved (or no answer, or the feature is off) = nothing is drawn.
   - /review (the page of the link in the delivered-order letter, shell in /opt/shop-consent/review.html; the link is /review#o=<order>&t=<token>[&r=1..5], the token lives in the address FRAGMENT so no server log and no Referer ever has it): "How was your order?" with a hidden 1-5
     rating and, for each product of the order, a review form. Opening the page writes nothing; only the buttons do (POST /api/review/rating and
     /api/review/submit). Everything that comes from the server is put into the page with textContent.
   Plain browser JS (var/function): no build step, no dependencies, no eval, no external resources. */
(function (root) {
  'use strict';

  /* ---------- pure logic (unit-tested in node: test/reviews-js.test.cjs) ---------- */

  var STAR = String.fromCharCode(0x2605);
  var TEXT = {
    heading: 'Customer reviews',
    verified: 'Verified purchase',
    note: 'For research use only. Reviews describe ordering, packaging and product quality.',
    invalid: 'This link is not valid. Please use the link in your delivered-order email.',
    busy: 'Too many attempts. Please try again in a little while.',
    unavailable: 'We could not load this page. Please try again in a minute.',
    loading: 'Loading...',
    askPrefix: 'How was your order ',
    askSuffix: '?',
    privateNote: 'Your rating is private. Only our team reads it; it is never shown on the site.',
    pickStar: 'Please choose 1 to 5 stars.',
    commentLabel: 'Anything you would like to add? (optional)',
    sendRating: 'Send rating',
    updateRating: 'Update rating',
    sending: 'Sending...',
    ratingSaved: 'Thank you. Your rating was saved. You can change it for 14 days using the same link.',
    ratingLocked: 'Your rating is saved. It can no longer be changed.',
    reviewHeading: 'Review a product',
    reviewRuo: 'Research use only: please describe product quality, packaging and delivery. Do not describe use on humans or dosing.',
    writeReview: 'Write a review',
    cancel: 'Cancel',
    reviewLabel: 'Your review (20 to 1000 characters)',
    nameLabel: 'Name shown with your review',
    consent: 'I agree this review may be published on the site.',
    reviewHint: 'Your review appears on the product page after our team approves it. Your email address is never shown.',
    submit: 'Submit review',
    reviewSent: 'Thank you. Your review was sent and will appear after our team approves it.',
    alreadySent: 'Review sent',
    tooShort: 'Please write at least 20 characters.',
    tooLong: 'Please keep the review to 1000 characters.',
    badName: 'Please enter a name of 2 to 30 characters, for example "Alex K.".',
    needConsent: 'Please tick the box to agree to publication.',
    fail: 'Something went wrong. Please try again.',
    locked: 'This rating can no longer be changed.',
    duplicate: 'You have already reviewed this product.'
  };
  var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

  function slugFromPath(pathname) {
    if (typeof pathname !== 'string') return '';
    var m = /^\/products\/([a-z0-9][a-z0-9-]*)(?:\.html)?\/?$/i.exec(pathname);
    return m ? m[1].toLowerCase() : '';
  }
  function isReviewPage(pathname) {
    return pathname === '/review' || pathname === '/review/';
  }
  /* The link of the letter: the fragment #o=<order number>&t=<token>[&r=1..5] (location.hash). Only the fragment is read: the letters that carry this form are
     the only ones there are. Anything that does not have the shape of one is dropped. */
  function parseLink(hash) {
    var out = { o: '', t: '', r: 0 };
    var s = typeof hash === 'string' && hash.charAt(0) === '#' ? hash.slice(1) : '';   /* only a fragment counts: a query is not a link */
    var parts = s ? s.split('&') : [], i, kv, k, v;
    for (i = 0; i < parts.length; i++) {
      kv = parts[i].split('=');
      k = kv[0];
      try { v = decodeURIComponent((kv.slice(1).join('=') || '').replace(/\+/g, ' ')); } catch (e) { v = ''; }
      if (k === 'o' && /^[A-Za-z0-9._-]{1,64}$/.test(v)) out.o = v;
      else if (k === 't' && /^[A-Za-z0-9_-]{32}$/.test(v)) out.t = v;
      else if (k === 'r' && /^[1-5]$/.test(v)) out.r = Number(v);
    }
    return out;
  }
  /* "2026-10" (what the server sends; a full date is read too) -> "October 2026". A month, not a day: less to correlate with an order. */
  function formatMonth(iso) {
    var m = /^(\d{4})-(\d{2})(?:-\d{2})?$/.exec(String(iso || ''));
    if (!m) return '';
    var n = Number(m[2]);
    return n >= 1 && n <= 12 ? MONTHS[n - 1] + ' ' + m[1] : '';
  }
  /* The answer of GET /api/reviews: only a well-formed list is trusted; preview true = test mode, shown only to a browser that opted in. */
  function parseReviews(json) {
    if (!json || typeof json !== 'object' || !Array.isArray(json.reviews)) return null;
    var list = [], i, r;
    for (i = 0; i < json.reviews.length; i++) {
      r = json.reviews[i];
      if (r && typeof r.text === 'string' && r.text && typeof r.displayName === 'string') list.push({ displayName: r.displayName, text: r.text, date: typeof r.date === 'string' ? r.date : '' });
    }
    return { reviews: list, preview: json.preview === true };
  }
  function shouldShow(parsed, previewFlag) {
    if (!parsed || !parsed.reviews.length) return false;
    if (parsed.preview && previewFlag !== '1') return false;
    return true;
  }
  function checkReview(v) {
    var text = String(v && v.text || '').replace(/^\s+|\s+$/g, '');
    if (text.length < 20) return { ok: false, error: TEXT.tooShort };
    if (text.length > 1000) return { ok: false, error: TEXT.tooLong };
    var name = String(v && v.name || '').replace(/\s+/g, ' ').replace(/^\s+|\s+$/g, '');
    if (name.length < 2 || name.length > 30 || /[@<>\/\\0-9]/.test(name)) return { ok: false, error: TEXT.badName };
    if (v.consent !== true) return { ok: false, error: TEXT.needConsent };
    return { ok: true, text: text, name: name };
  }
  function ratingPayload(link, r, comment) {
    return { o: link.o, t: link.t, r: r, comment: String(comment || '').replace(/^\s+|\s+$/g, '') };
  }
  function reviewPayload(link, slug, v) {
    return { o: link.o, t: link.t, slug: slug, text: v.text, displayName: v.name, consent: true };
  }
  /* The words under a form for each outcome; a 400 carries the server's own sentence. */
  function replyText(status, serverError) {
    if (status === 404) return TEXT.invalid;
    if (status === 429) return TEXT.busy;
    if (status === 409) return serverError ? String(serverError) : TEXT.duplicate;
    if (status === 400 && serverError) return String(serverError);
    return TEXT.fail;
  }

  var api = {
    TEXT: TEXT, slugFromPath: slugFromPath, isReviewPage: isReviewPage, parseLink: parseLink, formatMonth: formatMonth, parseReviews: parseReviews,
    shouldShow: shouldShow, checkReview: checkReview, ratingPayload: ratingPayload, reviewPayload: reviewPayload, replyText: replyText
  };

  /* ---------- DOM parts: every piece of server text goes through textContent ---------- */

  function el(doc, tag, cls, text) {
    var e = doc.createElement(tag);
    if (cls) e.className = cls;
    if (text !== undefined && text !== null) e.textContent = text;
    return e;
  }
  function clear(node) { while (node.firstChild) node.removeChild(node.firstChild); }

  var CSS =
    '.brv-wrap{max-width:860px;margin:40px auto 8px;padding:0 20px;box-sizing:border-box;color:#1F1F1F}' +
    '.brv-wrap *{box-sizing:border-box}' +
    '.brv-wrap h2{font-family:Fraunces,Georgia,serif;font-size:22px;margin:0 0 12px;color:#1F1F1F}' +
    '.brv-item{border-bottom:1px solid #E8E2D8;padding:14px 0}' +
    '.brv-head{display:flex;flex-wrap:wrap;align-items:center;gap:6px 10px;margin:0 0 6px;font-size:14px}' +
    '.brv-name{font-weight:700}' +
    '.brv-badge{display:inline-block;padding:2px 9px;border-radius:999px;background:#FAF3E0;border:1px solid #E6D3A3;color:#7A5C12;font-size:12px;font-weight:600}' +
    '.brv-date{color:#6B6B6B;font-size:13px}' +
    '.brv-text{margin:0;font-size:14.5px;line-height:1.65;color:#4A4A4A;white-space:pre-line;overflow-wrap:anywhere}' +
    '.brv-note{margin:14px 0 0;font-size:12.5px;line-height:1.5;color:#6B6B6B}' +
    '@media(max-width:390px){.brv-wrap{padding:0 16px}}' +
    /* the /review page */
    '.brv-page{max-width:640px;margin:0 auto;padding:24px 16px 56px;color:#1F1F1F;font-size:16px;line-height:1.5;box-sizing:border-box}' +
    '.brv-page *{box-sizing:border-box}' +
    '.brv-page h1{font-family:Fraunces,Georgia,serif;font-size:26px;line-height:1.25;margin:0 0 8px;font-weight:600}' +
    '.brv-page h2{font-family:Fraunces,Georgia,serif;font-size:21px;margin:34px 0 6px;font-weight:600}' +
    '.brv-page p{margin:0 0 12px}' +
    '.brv-muted{color:#6B6B6B;font-size:14px}' +
    '.brv-card{background:#fff;border:1px solid #E8E2D8;border-radius:14px;padding:16px;margin:12px 0}' +
    '.brv-stars{display:flex;gap:4px;margin:12px 0}' +
    '.brv-star{width:48px;height:48px;padding:0;border:1px solid #E8E2D8;border-radius:12px;background:#fff;color:#C9C3B6;font-size:28px;line-height:1;cursor:pointer}' +
    '.brv-star.on{color:#B8892B;border-color:#D9BE7A;background:#FBF6E8}' +
    '.brv-star:focus-visible{outline:2px solid #1F1F1F;outline-offset:2px}' +
    '.brv-star[disabled]{cursor:default}' +
    '.brv-label{display:block;margin:14px 0 6px;font-size:14px;font-weight:600}' +
    '.brv-input,.brv-area{display:block;width:100%;padding:11px 12px;border:1.5px solid #D6D0C3;border-radius:12px;background:#fff;color:#1F1F1F;font:inherit;font-size:16px}' +
    '.brv-area{min-height:110px;resize:vertical}' +
    '.brv-input:focus,.brv-area:focus{outline:2px solid #1F1F1F;outline-offset:1px}' +
    '.brv-count{margin:4px 0 0;font-size:12.5px;color:#6B6B6B;text-align:right}' +
    '.brv-check{display:flex;gap:10px;align-items:flex-start;margin:14px 0 6px;font-size:14.5px}' +
    '.brv-check input{width:22px;height:22px;margin:1px 0 0;flex:0 0 auto;accent-color:#1F1F1F}' +
    '.brv-btn{display:inline-block;min-height:48px;padding:0 24px;border:0;border-radius:999px;background:#1F1F1F;color:#fff;font:inherit;font-size:15px;font-weight:700;cursor:pointer}' +
    '.brv-btn.ghost{background:#fff;color:#1F1F1F;border:1.5px solid #1F1F1F}' +
    '.brv-btn[disabled]{opacity:.55;cursor:default}' +
    '.brv-row{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin-top:14px}' +
    '.brv-msg{margin:12px 0 0;font-size:14.5px;font-weight:600}' +
    '.brv-msg.ok{color:#7A5C12}' +
    '.brv-msg.err{color:#9B2C2C}' +
    '.brv-prod{display:flex;flex-wrap:wrap;gap:8px 12px;align-items:center;justify-content:space-between}' +
    '.brv-prod b{font-size:16px}' +
    '.brv-page [hidden]{display:none}';

  function css(doc) {
    if (doc.getElementById('brv-style')) return;
    var st = el(doc, 'style', '', CSS);
    st.id = 'brv-style';
    (doc.head || doc.documentElement).appendChild(st);
  }

  /* --- the product card: the block of approved reviews --- */
  function buildBlock(doc, list) {
    var wrap = el(doc, 'section', 'brv-wrap');
    wrap.id = 'blr-reviews';
    wrap.setAttribute('aria-labelledby', 'blr-reviews-title');
    var h = el(doc, 'h2', '', TEXT.heading);
    h.id = 'blr-reviews-title';
    wrap.appendChild(h);
    var i, r, item, head;
    for (i = 0; i < list.length; i++) {
      r = list[i];
      item = el(doc, 'div', 'brv-item');
      head = el(doc, 'div', 'brv-head');
      head.appendChild(el(doc, 'span', 'brv-name', r.displayName));
      head.appendChild(el(doc, 'span', 'brv-badge', TEXT.verified));
      var when = formatMonth(r.date);
      if (when) head.appendChild(el(doc, 'span', 'brv-date', when));
      item.appendChild(head);
      item.appendChild(el(doc, 'p', 'brv-text', r.text));
      wrap.appendChild(item);
    }
    wrap.appendChild(el(doc, 'p', 'brv-note', TEXT.note));
    return wrap;
  }
  /* Before the "pairs well" rail (right after the FAQ); else the end of <main>; else before the footer. Returns false when there is no place yet. */
  function placeBlock(doc, block) {
    var rail = doc.getElementById('productRail');
    if (rail && rail.parentNode) { rail.parentNode.insertBefore(block, rail); return true; }
    var main = doc.getElementById('main');
    if (main) { main.appendChild(block); return true; }
    var foot = doc.getElementById('site-footer');
    if (foot && foot.parentNode) { foot.parentNode.insertBefore(block, foot); return true; }
    return false;
  }
  function mountWidget(doc, win, slug) {
    var fetchFn = win.fetch;
    if (typeof fetchFn !== 'function') return;
    fetchFn.call(win, '/api/reviews?slug=' + encodeURIComponent(slug), { credentials: 'same-origin' })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (j) {
        var parsed = parseReviews(j), flag = '';
        try { flag = win.localStorage.getItem('blr_reviews_preview') || ''; } catch (e) { flag = ''; }
        if (!shouldShow(parsed, flag)) return;
        css(doc);
        var block = buildBlock(doc, parsed.reviews);
        var tries = 0;
        (function attach() {
          if (placeBlock(doc, block)) return;
          if (++tries < 6) win.setTimeout(attach, 500);
        })();
      })
      .catch(function () { /* no answer: nothing is drawn */ });
  }

  /* --- the /review page --- */
  function request(win, method, url, body) {
    var init = { method: method, credentials: 'same-origin' };
    if (body !== undefined) { init.headers = { 'Content-Type': 'application/json' }; init.body = JSON.stringify(body); }
    return win.fetch(url, init).then(function (r) {
      return r.json().then(function (j) { return { status: r.status, json: j }; }, function () { return { status: r.status, json: null }; });
    }, function () { return { status: 0, json: null }; });
  }
  function say(node, kind, text) {
    node.className = 'brv-msg' + (kind ? ' ' + kind : '');
    node.textContent = text || '';
  }

  function buildRating(doc, win, link, data, app) {
    var card = el(doc, 'div', 'brv-card');
    var existing = data.rating || null;
    var locked = !!(existing && existing.locked);
    var chosen = link.r || (existing ? existing.r : 0);
    var group = el(doc, 'div', 'brv-stars');
    group.setAttribute('role', 'radiogroup');
    group.setAttribute('aria-label', 'Rating from 1 to 5');
    var buttons = [], i;
    function paint() {
      for (i = 0; i < buttons.length; i++) {
        var on = i + 1 <= chosen;
        buttons[i].className = 'brv-star' + (on ? ' on' : '');
        buttons[i].setAttribute('aria-checked', chosen === i + 1 ? 'true' : 'false');
      }
    }
    function pick(n) { return function () { if (locked) return; chosen = n; paint(); }; }
    for (i = 0; i < 5; i++) {
      var b = el(doc, 'button', 'brv-star', STAR);
      b.setAttribute('type', 'button');
      b.setAttribute('role', 'radio');
      b.setAttribute('aria-label', (i + 1) + (i === 0 ? ' star' : ' stars'));
      if (locked) b.setAttribute('disabled', 'disabled');
      b.addEventListener('click', pick(i + 1));
      buttons.push(b);
      group.appendChild(b);
    }
    paint();
    card.appendChild(group);
    var label = el(doc, 'label', 'brv-label', TEXT.commentLabel);
    label.setAttribute('for', 'brv-comment');
    var area = el(doc, 'textarea', 'brv-area');
    area.id = 'brv-comment';
    area.setAttribute('maxlength', '1000');
    area.value = existing ? existing.comment || '' : '';
    if (locked) area.setAttribute('disabled', 'disabled');
    var msg = el(doc, 'p', 'brv-msg');
    msg.setAttribute('role', 'status');
    card.appendChild(label);
    card.appendChild(area);
    if (locked) {
      say(msg, 'ok', TEXT.ratingLocked);
    } else {
      var send = el(doc, 'button', 'brv-btn', existing ? TEXT.updateRating : TEXT.sendRating);
      send.setAttribute('type', 'button');
      var busy = false;
      send.addEventListener('click', function () {
        if (busy) return;
        if (!chosen) { say(msg, 'err', TEXT.pickStar); return; }
        busy = true; send.setAttribute('disabled', 'disabled'); say(msg, '', TEXT.sending);
        request(win, 'POST', '/api/review/rating', ratingPayload(link, chosen, area.value)).then(function (res) {
          busy = false; send.removeAttribute('disabled');
          if (res.status === 200 && res.json && res.json.ok === true) { send.textContent = TEXT.updateRating; say(msg, 'ok', TEXT.ratingSaved); }
          else if (res.status === 409) say(msg, 'err', TEXT.locked);
          else say(msg, 'err', replyText(res.status, res.json && res.json.error));
        });
      });
      var row = el(doc, 'div', 'brv-row');
      row.appendChild(send);
      card.appendChild(row);
    }
    card.appendChild(msg);
    return card;
  }

  function buildProduct(doc, win, link, data, item, done) {
    var card = el(doc, 'div', 'brv-card');
    var top = el(doc, 'div', 'brv-prod');
    top.appendChild(el(doc, 'b', '', item.name));
    var slot = el(doc, 'span', '');
    top.appendChild(slot);
    card.appendChild(top);
    var formBox = el(doc, 'div', '');
    card.appendChild(formBox);
    function sentState() { clear(slot); slot.appendChild(el(doc, 'span', 'brv-badge', TEXT.alreadySent)); clear(formBox); }
    if (done[item.slug]) { sentState(); return card; }
    var open = el(doc, 'button', 'brv-btn ghost', TEXT.writeReview);
    open.setAttribute('type', 'button');
    slot.appendChild(open);
    function showForm() {
      clear(formBox);
      var lab = el(doc, 'label', 'brv-label', TEXT.reviewLabel);
      var area = el(doc, 'textarea', 'brv-area');
      area.id = 'brv-text-' + item.slug;
      lab.setAttribute('for', area.id);
      area.setAttribute('maxlength', '1000');
      var count = el(doc, 'p', 'brv-count', '0 / 1000');
      area.addEventListener('input', function () { count.textContent = String(area.value.length) + ' / 1000'; });
      var nlab = el(doc, 'label', 'brv-label', TEXT.nameLabel);
      var name = el(doc, 'input', 'brv-input');
      name.id = 'brv-name-' + item.slug;
      nlab.setAttribute('for', name.id);
      name.setAttribute('type', 'text');
      name.setAttribute('maxlength', '30');
      name.value = data.defaultName || '';
      var checkRow = el(doc, 'label', 'brv-check');
      var box = el(doc, 'input', '');
      box.setAttribute('type', 'checkbox');
      checkRow.appendChild(box);
      checkRow.appendChild(el(doc, 'span', '', TEXT.consent));
      var ruo = el(doc, 'p', 'brv-muted', TEXT.reviewRuo);
      var hint = el(doc, 'p', 'brv-muted', TEXT.reviewHint);
      var msg = el(doc, 'p', 'brv-msg');
      msg.setAttribute('role', 'status');
      var go = el(doc, 'button', 'brv-btn', TEXT.submit);
      go.setAttribute('type', 'button');
      var cancel = el(doc, 'button', 'brv-btn ghost', TEXT.cancel);
      cancel.setAttribute('type', 'button');
      cancel.addEventListener('click', function () { clear(formBox); slot.appendChild(open); });
      var busy = false;
      go.addEventListener('click', function () {
        if (busy) return;
        var v = checkReview({ text: area.value, name: name.value, consent: !!box.checked });
        if (!v.ok) { say(msg, 'err', v.error); return; }
        busy = true; go.setAttribute('disabled', 'disabled'); say(msg, '', TEXT.sending);
        request(win, 'POST', '/api/review/submit', reviewPayload(link, item.slug, v)).then(function (res) {
          busy = false; go.removeAttribute('disabled');
          if (res.status === 200 && res.json && res.json.ok === true) { done[item.slug] = true; sentState(); formBox.appendChild(el(doc, 'p', 'brv-msg ok', TEXT.reviewSent)); }
          else if (res.status === 409) { done[item.slug] = true; sentState(); formBox.appendChild(el(doc, 'p', 'brv-msg', replyText(409, res.json && res.json.error))); }
          else say(msg, 'err', replyText(res.status, res.json && res.json.error));
        });
      });
      var row = el(doc, 'div', 'brv-row');
      row.appendChild(go); row.appendChild(cancel);
      [lab, area, count, nlab, name, checkRow, ruo, hint, row, msg].forEach(function (n) { formBox.appendChild(n); });
      try { area.focus(); } catch (e) { /* ignore */ }
    }
    open.addEventListener('click', function () { if (open.parentNode === slot) slot.removeChild(open); showForm(); });
    return card;
  }

  function mountPage(doc, win) {
    var app = doc.getElementById('review-app');
    if (!app) return;
    css(doc);
    var link = parseLink(win.location.hash);
    function fail(text) { clear(app); app.appendChild(el(doc, 'p', '', text)); }
    if (!link.o || !link.t) { fail(TEXT.invalid); return; }
    clear(app);
    app.appendChild(el(doc, 'p', 'brv-muted', TEXT.loading));
    request(win, 'POST', '/api/review/order', { o: link.o, t: link.t }).then(function (res) {
      if (res.status === 404) { fail(TEXT.invalid); return; }
      if (res.status === 429) { fail(TEXT.busy); return; }
      var d = res.json;
      if (res.status !== 200 || !d || typeof d.orderNumber !== 'string' || !Array.isArray(d.items)) { fail(TEXT.unavailable); return; }
      clear(app);
      app.appendChild(el(doc, 'h1', '', TEXT.askPrefix + d.orderNumber + TEXT.askSuffix));
      if (d.firstName) app.appendChild(el(doc, 'p', '', 'Hi ' + d.firstName + ', thank you for your order.'));
      app.appendChild(buildRating(doc, win, link, d, app));
      app.appendChild(el(doc, 'p', 'brv-muted', TEXT.privateNote));
      if (d.items.length) {
        app.appendChild(el(doc, 'h2', '', TEXT.reviewHeading));
        app.appendChild(el(doc, 'p', 'brv-muted', TEXT.reviewRuo));
        var done = {}, i;
        for (i = 0; i < (d.reviewed || []).length; i++) done[d.reviewed[i]] = true;
        for (i = 0; i < d.items.length; i++) {
          if (d.items[i] && typeof d.items[i].slug === 'string' && typeof d.items[i].name === 'string') app.appendChild(buildProduct(doc, win, link, d, d.items[i], done));
        }
      }
    });
  }

  api.buildBlock = buildBlock; api.placeBlock = placeBlock; api.mountWidget = mountWidget; api.mountPage = mountPage;
  if (typeof module === 'object' && module && module.exports) module.exports = api;

  /* ---------- start ---------- */
  if (typeof window === 'undefined' || !window.document) return;
  if (window.BLRReviews) return;   /* already injected on this page */
  var doc = window.document, path = window.location.pathname;
  var slug = slugFromPath(path);
  if (!slug && !isReviewPage(path)) return;
  window.BLRReviews = { version: 1 };
  function start() {
    if (slug) mountWidget(doc, window, slug);
    else mountPage(doc, window);
  }
  if (doc.readyState === 'loading') doc.addEventListener('DOMContentLoaded', start);
  else start();
})(typeof window !== 'undefined' ? window : this);
